#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WallpaperGenerator.Android.Resource", IsApplication=true)]

namespace WallpaperGenerator.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000b
			public const int backMenuItem = 2131165195;
			
			// aapt resource value: 0x7f070005
			public const int changeColorMenuItem = 2131165189;
			
			// aapt resource value: 0x7f070002
			public const int formulaTextView = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int generateMenuItem = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int renderMenuItem = 2131165188;
			
			// aapt resource value: 0x7f070009
			public const int saveMenuItem = 2131165193;
			
			// aapt resource value: 0x7f070000
			public const int scrollView = 2131165184;
			
			// aapt resource value: 0x7f070007
			public const int setAsWallpaperMenuItem = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int shareMenuItem = 2131165192;
			
			// aapt resource value: 0x7f070006
			public const int transformMenuItem = 2131165190;
			
			// aapt resource value: 0x7f07000a
			public const int viewGalleryMenuItem = 2131165194;
			
			// aapt resource value: 0x7f070001
			public const int wallpaperImageView = 2131165185;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int Main = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040009
			public const int Back = 2130968585;
			
			// aapt resource value: 0x7f040004
			public const int ChangeColors = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int Generate = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Render = 2130968578;
			
			// aapt resource value: 0x7f040007
			public const int Save = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int SetAsWallpaper = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int Share = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int Transform = 2130968579;
			
			// aapt resource value: 0x7f040008
			public const int ViewGallery = 2130968584;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int AppBaseTheme = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
