#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WallpaperGenerator.UI.Android.Resource", IsApplication=true)]

namespace WallpaperGenerator.UI.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Android.Utilities.Resource.Dimension.activity_horizontal_margin = global::WallpaperGenerator.UI.Android.Resource.Dimension.activity_horizontal_margin;
			global::Android.Utilities.Resource.Dimension.activity_vertical_margin = global::WallpaperGenerator.UI.Android.Resource.Dimension.activity_vertical_margin;
			global::Android.Utilities.Resource.Dimension.default_text_size = global::WallpaperGenerator.UI.Android.Resource.Dimension.default_text_size;
			global::Android.Utilities.Resource.Dimension.small_text_size = global::WallpaperGenerator.UI.Android.Resource.Dimension.small_text_size;
			global::Android.Utilities.Resource.Dimension.very_small_text_size = global::WallpaperGenerator.UI.Android.Resource.Dimension.very_small_text_size;
			global::Android.Utilities.Resource.Id.errorScrollView = global::WallpaperGenerator.UI.Android.Resource.Id.errorScrollView;
			global::Android.Utilities.Resource.Id.errorTextView = global::WallpaperGenerator.UI.Android.Resource.Id.errorTextView;
			global::Android.Utilities.Resource.Layout.CrashReport = global::WallpaperGenerator.UI.Android.Resource.Layout.CrashReport;
			global::Android.Utilities.Resource.String.CrashReport = global::WallpaperGenerator.UI.Android.Resource.String.CrashReport;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int activity_horizontal_margin = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int activity_vertical_margin = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int default_text_size = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int small_text_size = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int very_small_text_size = 2130968580;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080007
			public const int changeColorsButton = 2131230727;
			
			// aapt resource value: 0x7f080000
			public const int errorScrollView = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int errorTextView = 2131230721;
			
			// aapt resource value: 0x7f08000f
			public const int feedbackMenuItem = 2131230735;
			
			// aapt resource value: 0x7f080004
			public const int formulaTextView = 2131230724;
			
			// aapt resource value: 0x7f080006
			public const int generateButton = 2131230726;
			
			// aapt resource value: 0x7f080003
			public const int imageView = 2131230723;
			
			// aapt resource value: 0x7f08000c
			public const int openGalleryMenuItem = 2131230732;
			
			// aapt resource value: 0x7f08000e
			public const int rateAppMenuItem = 2131230734;
			
			// aapt resource value: 0x7f08000d
			public const int removeAdsMenuItem = 2131230733;
			
			// aapt resource value: 0x7f080005
			public const int renderTimeTextView = 2131230725;
			
			// aapt resource value: 0x7f08000a
			public const int saveMenuItem = 2131230730;
			
			// aapt resource value: 0x7f080002
			public const int scrollView = 2131230722;
			
			// aapt resource value: 0x7f080009
			public const int setAsWallpaperButton = 2131230729;
			
			// aapt resource value: 0x7f08000b
			public const int shareMenuItem = 2131230731;
			
			// aapt resource value: 0x7f080008
			public const int transformButton = 2131230728;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CrashReport = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int Main = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int Back = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int ChangeColors = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int CrashReport = 2131034112;
			
			// aapt resource value: 0x7f05000f
			public const int Feedback = 2131034127;
			
			// aapt resource value: 0x7f050002
			public const int Generate = 2131034114;
			
			// aapt resource value: 0x7f05000b
			public const int OpenGallery = 2131034123;
			
			// aapt resource value: 0x7f05000e
			public const int RateApp = 2131034126;
			
			// aapt resource value: 0x7f05000c
			public const int RemoveAds = 2131034124;
			
			// aapt resource value: 0x7f050003
			public const int Render = 2131034115;
			
			// aapt resource value: 0x7f05000a
			public const int Save = 2131034122;
			
			// aapt resource value: 0x7f050010
			public const int SavingWallpaper = 2131034128;
			
			// aapt resource value: 0x7f050007
			public const int SetAsWallpaper = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int SettingWallpaper = 2131034120;
			
			// aapt resource value: 0x7f05000d
			public const int Settings = 2131034125;
			
			// aapt resource value: 0x7f050009
			public const int Share = 2131034121;
			
			// aapt resource value: 0x7f050012
			public const int ShareMessage = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int ShareSubject = 2131034129;
			
			// aapt resource value: 0x7f050013
			public const int ShareTitle = 2131034131;
			
			// aapt resource value: 0x7f050004
			public const int Transform = 2131034116;
			
			// aapt resource value: 0x7f050014
			public const int Wait = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int WallpaperWillBeReady = 2131034133;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int AppBaseTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int AppBaseTheme_ActionBar = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int ToolBarButton = 2131099650;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
